# Generated by Django 3.2.8 on 2022-08-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='435ca94b-fd13-45a3-ac19-64d7e0303485', max_length=150, unique=True, verbose_name='username'),
        ),
    ]
