# Generated by Django 3.2.8 on 2022-10-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='1e15eb6f-d7ac-4fb3-988e-b4e0f124b5ab', max_length=150, unique=True, verbose_name='username'),
        ),
    ]
